-- Stats.ku (ScreenTime.ku) Database Schema for Supabase PostgreSQL
-- Copy and run this script in your Supabase SQL Editor (https://supabase.com)

-- 1. Create screen_time_usage table
create table if not exists public.screen_time_usage (
    id bigint generated by default as identity primary key,
    device_id text not null,
    usage_date date not null,
    package_name text not null,
    app_name text,
    total_time_foreground bigint not null default 0,
    usage_minutes integer not null default 0,
    open_count integer default 1,
    first_used_at timestamptz,
    last_used_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(device_id, usage_date, package_name)
);

-- 2. Create performance indexes
create index if not exists idx_screen_time_device_date
on public.screen_time_usage(device_id, usage_date);

create index if not exists idx_screen_time_usage_date
on public.screen_time_usage(usage_date);

-- 3. Enable Row Level Security (RLS)
alter table public.screen_time_usage enable row level security;

-- 4. Create RLS Policies for Anon / Client access
create policy "Allow anon insert/upsert screen_time_usage"
on public.screen_time_usage for insert
with check (true);

create policy "Allow anon select screen_time_usage"
on public.screen_time_usage for select
using (true);

create policy "Allow anon update screen_time_usage"
on public.screen_time_usage for update
using (true);
