import { createClient, SupabaseClient } from '@supabase/supabase-js';

const defaultUrl = import.meta.env.VITE_SUPABASE_URL || localStorage.getItem('stats_ku_supabase_url') || '';
const defaultAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || localStorage.getItem('stats_ku_supabase_key') || '';

export let supabase: SupabaseClient | null = (defaultUrl && defaultAnonKey) 
  ? createClient(defaultUrl, defaultAnonKey)
  : null;

export function updateSupabaseConfig(url: string, anonKey: string): SupabaseClient | null {
  if (!url || !anonKey) {
    supabase = null;
    return null;
  }
  localStorage.setItem('stats_ku_supabase_url', url);
  localStorage.setItem('stats_ku_supabase_key', anonKey);
  supabase = createClient(url, anonKey);
  return supabase;
}

export const SUPABASE_SQL_SCHEMA = `-- Stats.ku (ScreenTime.ku) Database Schema
-- Run this in your Supabase SQL Editor

create table if not exists public.screen_time_usage (
    id bigint generated by default as identity primary key,

    device_id text not null,

    usage_date date not null,

    package_name text not null,

    app_name text,

    total_time_foreground bigint not null default 0,

    usage_minutes integer not null default 0,

    open_count integer default 1,

    first_used_at timestamptz,

    last_used_at timestamptz,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique(device_id, usage_date, package_name)
);

create index if not exists idx_screen_time_device_date
on public.screen_time_usage(device_id, usage_date);

create index if not exists idx_screen_time_usage_date
on public.screen_time_usage(usage_date);

-- Enable Row Level Security (RLS)
alter table public.screen_time_usage enable row level security;

-- Allow anonymous / authenticated clients to read and insert/upsert their own device records
create policy "Allow anon insert/upsert screen_time_usage"
on public.screen_time_usage for insert
with check (true);

create policy "Allow anon select screen_time_usage"
on public.screen_time_usage for select
using (true);

create policy "Allow anon update screen_time_usage"
on public.screen_time_usage for update
using (true);
`;
